# Generated by Django 3.1.7 on 2022-06-30 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('go_app', '0003_auto_20220630_1519'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='signup',
            table='SignUp',
        ),
    ]
