# Generated by Django 3.1.7 on 2022-07-03 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('go_app', '0004_auto_20220630_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=100)),
                ('bus_no', models.IntegerField()),
                ('contact', models.BigIntegerField()),
                ('private', models.BooleanField()),
            ],
            options={
                'db_table': 'bus_detail',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taking_place', models.CharField(max_length=100)),
                ('reaching_place', models.CharField(max_length=100)),
                ('taking_time', models.TimeField()),
                ('reaching_time', models.TimeField()),
                ('time_taken', models.CharField(max_length=100)),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='go_app.busdetail')),
            ],
            options={
                'db_table': 'bus_schedule',
                'unique_together': {('taking_time', 'bus_id')},
            },
        ),
    ]
