# Generated by Django 3.1.7 on 2022-07-03 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('go_app', '0005_busdetails_timing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busdetails',
            old_name='busName',
            new_name='bus_name',
        ),
        migrations.RenameField(
            model_name='busdetails',
            old_name='busNo',
            new_name='bus_no',
        ),
        migrations.RenameField(
            model_name='timing',
            old_name='busId',
            new_name='bus_id',
        ),
        migrations.RenameField(
            model_name='timing',
            old_name='reachingPlace',
            new_name='reaching_place',
        ),
        migrations.RenameField(
            model_name='timing',
            old_name='reachingTime',
            new_name='reaching_time',
        ),
        migrations.RenameField(
            model_name='timing',
            old_name='takingPlace',
            new_name='taking_place',
        ),
        migrations.RenameField(
            model_name='timing',
            old_name='takingTime',
            new_name='taking_time',
        ),
        migrations.RenameField(
            model_name='timing',
            old_name='timeTaken',
            new_name='time_taken',
        ),
        migrations.AlterUniqueTogether(
            name='timing',
            unique_together={('taking_time', 'bus_id')},
        ),
    ]
