# Generated by Django 3.1.7 on 2022-07-03 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('go_app', '0005_busdetail_schedule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BusDetail',
            new_name='BusDetails',
        ),
    ]
