# Generated by Django 3.1.7 on 2022-07-03 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('go_app', '0006_auto_20220703_1525'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='busdetails',
            table='bus_details',
        ),
    ]
