# Generated by Django 3.1.7 on 2022-07-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go_app', '0007_auto_20220703_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetails',
            name='bus_no',
            field=models.CharField(max_length=100),
        ),
    ]
