# Generated by Django 4.0.5 on 2022-08-14 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('go_app', '0009_remove_signup_password_remove_signup_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user_id',
            new_name='user',
        ),
    ]
