# Generated by Django 3.1.7 on 2022-10-10 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('go_app', '0013_auto_20221010_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='bus_id',
            new_name='bus',
        ),
    ]
