# Generated by Django 4.0.5 on 2022-11-07 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('go_app', '0015_rename_user_busdetails_bus_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='bus',
            field=models.ForeignKey(default=50, on_delete=django.db.models.deletion.CASCADE, to='go_app.busdetails'),
            preserve_default=False,
        ),
    ]
